steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$COMMIT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

substitutions:
  _REGION: us-central1
  _SERVICE: chargrid
  _REPO: cloud-run-source-deploy

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE

options:
  logging: CLOUD_LOGGING_ONLY
